apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-8e78
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-imil-tenant/rhtap-demo-app/hacbs-test-project-8e78@sha256:b13fff0872216d1bfac9453e1c351023cb33ecbb000c2ac1755bb3c5e2ec8f87
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
