apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-8e78
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-8e78
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-8e78
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-8e78
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-8e78
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-imil-tenant/rhtap-demo-app/hacbs-test-project-8e78@sha256:b13fff0872216d1bfac9453e1c351023cb33ecbb000c2ac1755bb3c5e2ec8f87
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
