apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-8e78
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-8e78
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-8e78
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-8e78
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-8e78
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-imil-tenant/rhtap-demo-app/hacbs-test-project-8e78@sha256:e34df8988540667d3e86c984ad1bbd38ce0cc8e7f315d3bb24fd6d5e50a8a26c
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
